# Python Program to Add Two Matrices

In [50]:
x = [[1,2,3],
    [4 ,5,6,],
    [7,8,9],]
 
y = [[1,2,3],
    [4 ,5,6],
    [7,8,9]]

try:
    l = []
    for i in range(0 , len(x)):
        temp = []
        for z in range (0, len(x[i])):
            temp.append(x[i][z]+ y[i][z])
        l.append(temp)
    print(l)

except IndexError as e:
    print("\nMatrix are not of Same Length")
else:
    print("Two Matrices added successfully!")
    
finally:
    print("Code Execeuted Successfully")

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
Two Matrices added successfully!
Code Execeuted Successfully


# Python Program to Multiply Two Matrices

In [53]:
import numpy as np
x = [[1,2,3],
    [4 ,5,6,],
    [7,8,9],]
 
y = [[1,2,3],
    [4 ,5,6],
    [7,8,9]]


try:
        x =  np.matmul(x,y)
        print(x)

except IndexError as e:
    print("\nMatrix are not of Same Length")
else:
    print("Two Matrices added successfully!")
    
finally:
    print("Code Execeuted Successfully")

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Two Matrices added successfully!
Code Execeuted Successfully


# Python Program to Transpose a Matrix

In [57]:
import numpy as np
x = [[1,2,3],
    [4 ,5,6,],
    [7,8,9],]

np.array(x).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Python Program to Remove Punctuation From a String

In [103]:
l = [chr(c) for c in range(65, 90)] +  [chr(i) for i in range(97, 123) ] + [chr(32)]

In [108]:
str = "ab\"#$%&'()*+,-./cd:;<=>?@[\]^_`{|}~ef"

for i in range(len(str)):
    if str[i] not in l:
        str = str.replace(str[i], " ")
        
print(str)

ab              cd                 ef
